name: view_model
description: "view model for flutter. Simple and Lightweight & Cross - Widget Sharing & Automatic Resource Disposal"
version: 0.8.0-dev.2
homepage: https://github.com/lwj1994/flutter_view_model
repository: https://github.com/lwj1994/flutter_view_model
issue_tracker: https://github.com/lwj1994/flutter_view_model/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - state-management
  - view-model
  - caching
  - dependency-injection
  - vm

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  meta: any
  stack_trace: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  coverage:
  test:
