name: view_model
description: Everything is ViewModel. Enjoy automatic lifecycle
  management, prevent memory leaks, and share state effortlessly.
  Simple, lightweight, and powerful.
version: 0.12.0
homepage: https://github.com/lwj1994/flutter_view_model
repository: https://github.com/lwj1994/flutter_view_model
issue_tracker: https://github.com/lwj1994/flutter_view_model/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - state-management
  - view-model
  - caching
  - dependency-injection
  - vm

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  view_model_annotation: ^0.2.2
  stack_trace: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  coverage:
  test:
