name: view_model_generator
description: Automatically generate ViewModelProvider code from @genProvider annotations. Reduces boilerplate for the view_model package.
version: 0.13.0-dev.0
homepage: https://github.com/lwj1994/flutter_view_model/tree/main/packages/view_model_generator
repository: https://github.com/lwj1994/flutter_view_model/tree/main/packages/view_model_generator
issue_tracker: https://github.com/lwj1994/flutter_view_model/issues


environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  view_model_annotation:
    path: ../view_model_annotation
dependencies:
  analyzer: ^8.1.1
  source_gen: ^4.0.0
  build: ^4.0.0
  view_model_annotation: ^0.13.0-dev.0

dev_dependencies:
  build_runner: ^2.7.1
  source_gen_test: ^1.0.0
  test: ^1.24.0
