name: example
description: A simple example demonstrating how to use view_model_generator.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependency_overrides:
  view_model_annotation:
    path: ../../view_model_annotation

dependencies:
  flutter:
    sdk: flutter
  view_model:
    path: ../../view_model


dev_dependencies:
  build_runner: ^2.4.0
  view_model_generator:
    path: ../
