name: annotation_example
description: Example for view_model_annotation usage.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  view_model:
    path: ../../view_model
  view_model_annotation:
    path: ../

dev_dependencies:
  build_runner: ^2.4.0
  view_model_generator:
    path: ../../view_model_generator

dependency_overrides:
  view_model_annotation:
    path: ../
