name: view_model_annotation
description: Annotation package for view_model code generation.
version: 0.14.0-dev.1
homepage: https://github.com/lwj1994/flutter_view_model/tree/main/packages/view_model_annotation
repository: https://github.com/lwj1994/flutter_view_model/tree/main/packages/view_model_annotation
issue_tracker: https://github.com/lwj1994/flutter_view_model/issues

environment:
  sdk: ">=3.0.0 <4.0.0"


