name: view_model_annotation
description: Annotation package for view_model code generation.
version: 0.1.0
homepage: https://github.com/lwj1994/flutter_view_model
repository: https://github.com/lwj1994/flutter_view_model
issue_tracker: https://github.com/lwj1994/flutter_view_model/issues

environment:
  sdk: ">=3.0.0 <4.0.0"


