name: view_model_devtools_extension
description: DevTools extension for Flutter ViewModel library
version: 1.0.0
homepage: https://github.com/lwj1994/flutter_view_model
repository: https://github.com/lwj1994/flutter_view_model
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: any
  devtools_app_shared: any
  view_model:
    path: ../view_model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
